name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 82.198.228.57
          username: u162093132
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          # أضف هذا السطر ليتجاهل مشاكل البصمة الأمنية المتغيرة
          script_stop: true
          script: |
            cd ~/domains/syriashop0.com/laravel_code
            git fetch origin main
            git reset --hard origin/main
            php artisan config:cache
